### ISSUE TITLE
Gutter background color

### ISSUE THREAD

**Issue by armiller** [robneu/base16-eighties-one-dark#2]
First off, thanks for syntax theme. It seems to be the only proper implementation of Base16 Eighties on atom.io.

The only thing I noticed coming from Sublime was that the gutter background is a tad darker than the normal text background. Was this just a personal preference? It seems strange to follow the base colors and then darken one slightly just for the gutter. What are your thoughts on changing it to just `@base00`?

**Comment by robneu** [comment]
I think it was just a choice I made when I was setting things up. Might have been related to how the color scheme looked in Sublime, but it's been so long since I used Sublime I can't remember now. LoL

Switching it sounds fine to me. I'll try to get this updated later today.
